### ISSUE TITLE
RLP Support Meta Data actions

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/wasm-shim#10]
- [x] Missing envoy rate limiting actions required to implement authenticated rate limit 
* https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-ratelimit-action
* Attributes available at the wasm shim: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes

- [ ] Update user guide to include authenticated rate limit

#### dev notes
* `descriptor_from_actions` in [utils.rs](https://github.com/Kuadrant/wasm-shim/blob/main/src/utils.rs)

**Comment by eguzki** [comment]
Related issue: https://github.com/Kuadrant/kuadrant-controller/issues/144

**Comment by eguzki** [comment]
@rahulanand16nov  I wonder if we can close this as it was implemented in #22

**Comment by rahulanand16nov** [comment]
I was actually waiting for https://github.com/Kuadrant/kuadrant-controller/pull/184 but it's merged now. Closed :)
