### ISSUE TITLE
Fold subsequent calls to Limitador into a single one

### ISSUE THREAD

**Issue by alexsnaps** [Kuadrant/wasm-shim#145]

**Comment by alexsnaps** [comment]
@eguzki you said iirc you started on this, but couldn't find anything, is this still on your plate?

**Comment by eguzki** [comment]
Yes! working on this right now.

**Comment by eguzki** [comment]
v1.0 or v1.1? @alexsnaps

**Comment by alexsnaps** [comment]
v1.0... made it a should tho. Don't think it should be a blocker
