### ISSUE TITLE
FailureMode propagation and handling in services

### ISSUE THREAD

**Issue by adam-cattermole** [Kuadrant/wasm-shim#149]
There is a flaw in the logic to the handling of errors for each of the services - we should always propagate the error to the caller for the next action in the set.

Example; if there's two services defined, the first action being `FailureMode::Allow` followed by `FailureMode::Deny` and for any reason we have an issue in the [`process_grpc_response`](https://github.com/Kuadrant/wasm-shim/blob/main/src/service.rs#L55) function for the first service we call [`handle_error_on_grpc_response`](https://github.com/Kuadrant/wasm-shim/blob/main/src/service.rs#L85-L95) which will [`resume_http_request`](https://github.com/Kuadrant/wasm-shim/blob/main/src/service.rs#L92) ignoring the subsequent actions effectively allowing the request through.

This [error block](https://github.com/Kuadrant/wasm-shim/blob/main/src/service.rs#L70-L76) for example will also be hit if we have a timeout on our grpc call to the initial service (service code 14 with an empty message body).

**Comment by eguzki** [comment]
> This [error block](https://github.com/Kuadrant/wasm-shim/blob/main/src/service.rs#L70-L76) for example will also be hit if we have a timeout on our grpc call to the initial service (service code 14 with an empty message body).

That's because kuadrant's module does not check `status_code` in 

```rust
fn on_grpc_call_response(&mut self, token_id: u32, status_code: u32, resp_size: usize) {
```
The code should never reach `process_grpc_response` when `status_code` is other than ''OK'' (I think it is ''0'').

**Comment by adam-cattermole** [comment]
Agreed, but we also need to think about what the different return codes might mean for the expected outcome and whether the failure mode makes sense in each case - whether we can/should continue with subsequent actions or not
