### ISSUE TITLE
Implement `skip_if_absent` for the RequestHeaders action

### ISSUE THREAD

**Issue by eguzki** [Kuadrant/wasm-shim#29]
The [Envoys's RequestHeaders](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-ratelimit-action-requestheaders) action has a field called `skip_if_absent` that changes the behavior when enabled. 

The spec:
* It should be an optional field with a default value: `false`. 
* When `skip_if_absent` is `false`, the action behaves as it does now. When the header is absent, the entire descriptor is discarded, no matter what other action of the same configuration tell.
* When `skip_if_absent` is `true` and the header is not present in the request, the descriptor is not discarded, however the action does not generate any descriptor entry. This behavior can lead to an empty descriptor. That is allowed. An empty descriptor is still a valid descriptor. Rate limit service can be called with an empty descriptor. Rate limit request  with an empty descriptor
```
limitador_1  | [2023-02-02T11:30:32Z DEBUG limitador_server::envoy_rls::server] Request received: Request { metadata: MetadataMap { headers: {"te": "trailers", "grpc-timeout": "5000m", "content-type": "application/grpc", "x-envoy-internal": "true", "x-forwarded-for": "172.19.0.4", "x-envoy-expected-rq-timeout-ms": "5000"} }, message: RateLimitRequest { domain: "rls-domain-a", descriptors: [RateLimitDescriptor { entries: [], limit: None }], hits_addend: 1 }, extensions: Extensions }
```

Note the empty descriptor
```
descriptors: [RateLimitDescriptor { entries: [], limit: None }]
```

**Comment by alexsnaps** [comment]
This might not be relevant anymore, given [kuadrant-operator#179](https://github.com/Kuadrant/kuadrant-operator/issues/179), where the actions aren't exposed as such anymore
