### ISSUE TITLE
e2e tests

### ISSUE THREAD

**Issue by eguzki** [Kuadrant/wasm-shim#34]
Currently, only few unittests are run. 

In order to catch issues covering the integration of all the layers within the wasm module, e2e tests are required. 2e2 test can have different meaning and scope. As discussed internally, "real" e2e tests deplying kubernetes, envoy with the wasm filter and limitador to test the wasm module is complex and does not add much value in the context of this repo. These kind of e2e tests are wanted, required and provide value in the bigger picture of kuadrant. 

For the wasm module, we would need a test framework to wrap the wasm module and be able to test it as a black box and set some expectations on different integration points of the wasm module with external components. Namely, the returned response and grpc calls to the external rate limiting service.

**Comment by alexsnaps** [comment]
I'll give this [test framework](https://github.com/proxy-wasm/test-framework) a shot and see where this leads…

**Comment by eguzki** [comment]
Updated the description to accommodate to the latest defined scope of the e2e

**Comment by eguzki** [comment]
Done in https://github.com/Kuadrant/wasm-shim/pull/36

The framework is there, now we need to add more e2e to cover more (edge) cases
