### ISSUE TITLE
Selectors: support data types other than string from envoy attributes 

### ISSUE THREAD

**Issue by eguzki** [Kuadrant/wasm-shim#38]
Currently, only selectors that return string data type can be used.

From the [Envoys attributes](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes), examples can be `request.path`, `source.address` or `request.headers.<header-name>`. 

However, other attributes return a different type of data. Instances can be `request.time`, `request.size`, `source.port` or metadata based attributes.

**Comment by alexsnaps** [comment]
See https://github.com/Kuadrant/wasm-shim/pull/41

**Comment by alexsnaps** [comment]
see #60
