### ISSUE TITLE
Verify the gRPC calls from the wasm-shim do propagate the traceid

### ISSUE THREAD

**Issue by alexsnaps** [Kuadrant/wasm-shim#47]

**Comment by adam-cattermole** [comment]
Currently the trace headers are not propagated if envoy starts the trace, see the discussion here https://envoyproxy.slack.com/archives/CM2CQ4XJ5/p1707487817883799.

**Comment by adam-cattermole** [comment]
A minor follow up - I've investigated the option of generating the traceparent header ourselves and adding this to the request in wasm-shim. If for example we add the traceparent header here https://github.com/Kuadrant/wasm-shim/blob/main/src/filter/http_context.rs#L209 through `self.add_http_request_header()`, it still ends up being propagated back through to authorino.
