### ISSUE TITLE
Investigate adding and exporting metrics from a WASM module

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/wasm-shim#6]
In order to be able to observe what is happening at runtime via tools such as prometheus and grafana being able to expose some metrics around the WASM module would be useful. An example of this would be a counter that counts how often the module has been invoked for a particular host another would be to expose the number of failed requests etc

cc @rahulanand16nov

**Comment by rahulanand16nov** [comment]
EZ PZ 😎

**Comment by eguzki** [comment]
I think that https://github.com/Kuadrant/wasm-shim/issues/106 and https://github.com/Kuadrant/wasm-shim/issues/105 would cover this issue.
