### ISSUE TITLE
Add missing Apache-2.0 license

### ISSUE THREAD

**Issue by thomasmaas** [Kuadrant/wasm-shim#71]
As it says on the tin.

**Comment by eguzki** [comment]
Additionally, fix licensing issues reported by FOSSA https://app.fossa.com/projects/custom%2B162%2Fgit%2Bgithub.com%2FKuadrant%2Fwasm-shim/refs/branch/main/cebb46d08f7cb3567692c0e34fda113f975a857e/issues/licensing?page=1&count=20&sort=issue_count_desc&grouping=revision&status=active&filter%5Btype%5D%5B0%5D=policy_flag&revisionScanId=62727235

![Screenshot 2024-08-21 at 12-59-05 wasm-shim - Projects FOSSA](https://github.com/user-attachments/assets/9aa2ca53-ba23-45bc-95fe-81b5e00509e2)
