### ISSUE TITLE
Fix license issue reported by FOSSA

### ISSUE THREAD

**Issue by eguzki** [Kuadrant/wasm-shim#73]
Fix license issues reported by FOSSA https://app.fossa.com/projects/custom%2B162%2Fgit%2Bgithub.com%2FKuadrant%2Fwasm-shim/refs/branch/main/cebb46d08f7cb3567692c0e34fda113f975a857e/issues/licensing?page=1&count=20&sort=issue_count_desc&grouping=revision&status=active&filter%5Btype%5D%5B0%5D=policy_flag&revisionScanId=62727235

![Screenshot 2024-08-21 at 12-59-05 wasm-shim - Projects FOSSA](https://github.com/user-attachments/assets/9aa2ca53-ba23-45bc-95fe-81b5e00509e2)

**Comment by david-martin** [comment]
I have chosen to 'Ignore' all of these license issues in FOSSA as the dependencies all have dual licenses, for which a non GPL license is available.
All 3 have a BSD-style license available under dual license.
