### ISSUE TITLE
Make the timeout of the rate limit request configurable

### ISSUE THREAD

**Issue by roivaz** [Kuadrant/wasm-shim#93]
The current timeout value is `5s` and not configurable (see [code](https://github.com/Kuadrant/wasm-shim/blob/main/src/service.rs#L102)). Also, 5 seconds seems way too high. A more sensible default could be `20ms`, same as the envoy [ratelimit filter](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ratelimit/v3/rate_limit.proto#envoy-v3-api-msg-extensions-filters-http-ratelimit-v3-ratelimit) uses.

**Comment by alexsnaps** [comment]
To be considered whether we'd want 2 of these, or say one "per service", as I could see Authorino needing a different value than Limitador

**Comment by adam-cattermole** [comment]
I'd say that we include it as part of the [extension configuration](https://github.com/Kuadrant/wasm-shim/blob/main/src/configuration.rs#L531-L537) in the wasm-shim so that it's configurable by service, the same way as the failure mode.
